SELECT [Procedure_Code]
      --,[Procedure_Code_With_Decimal]
      --,[Procedure_Description]
      --,[Selection_Indicators]
      --,[Procedure_Prefix]
      ,[Chapter_Code]
      ,[Chapter_Description]
      ,[Group_Code]
      ,[Group_Description]
      --,[Sex_Absolute]
      --,[Sex_Scrutiny]
      --,[Status_Of_Operation]
      --,[Method_Of_Delivery]
      --,[Method_Of_Delivery_Code]
      ,min([OPCS_Version]) as [Min_OPCS_Version]
      --,[Import_Date]
      --,[Created_Date]
      ,min([Effective_From]) as [OPCS_Release_Date]
      --,[Effective_To]
      --,[Inferred_flag]
      --,[System_Effective_From]
      --,[System_Effective_To]
  FROM [HESMART].[Dim_Procedure]
  group by
	[Procedure_Code]
	,[Chapter_Code]
    ,[Chapter_Description]
    ,[Group_Code]
    ,[Group_Description]
